### ISSUE TITLE
Feedback Quiz Lv4-form

### ISSUE THREAD

**Issue by udiiin** [yunusbahtiar22/hsi-sandbox-lv4-1#1]
Halo Mas @yunusbahtiar22, terima kasih utk submissionnya...

Saya ada 1 feedback aja:

Utk state dari form values tidak perlu menggunakan `useReducer`, karena seharusnya sudah bisa full dihandle oleh `useForm`.  
Dan jg tidak perlu menggunakan context.

Silakan dicoba utk tidak menggunakan `useReducer` & `context`, manfaatkan `useForm`.  
Nanti ini bisa pakai 1 `useForm` di parentnya, yg isinya sudah mencakup keseluruhan step.

**Comment by yunusbahtiar22** [comment]
#6eead31

**Comment by yunomeister22** [comment]
baik mas @udiiin sudah ditindak lanjuti yaa disini 6eead312c9ff0d8ab3ab3f74c543a3bf44656db6

**Comment by udiiin** [comment]
Sipp mas, udah oke ✅
